- hosts: Kubernetes
  tasks:
  
  - name: Add repository
    become: yes
    shell: |
     cd /etc/yum.repos.d
     wget https://download.docker.com/linux/centos/docker-ce.repo
    tags:
      - final

  - name: Install docker
    become: yes
    yum:
     name: "{{ packages }}"
     state: present
    vars:
     packages:
      - docker-ce  
      - docker-ce-cli
      - containerd.io
    tags:
      - final

  - name: "Starting and enable docker service"
    become: yes
    service:
      name: "docker"
      state: started
      enabled: yes
    tags:
      - final

  - name: Give the permession to non root user to use docker
    become: yes
    shell: |
     usermod -a -G docker $USER
     docker ps
    tags:
      - final

  - name:  Configure the Docker daemon
    become: yes
    shell:
        cmd: |
          cat > /etc/docker/daemon.json << EOF
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
          EOF
    tags:
      - final

  - name: "restart docker service "
    become: yes
    service:
      name: "docker"
      state: restarted
    tags:
      - final
  
  - name: "copy shell script preparing install kubernetes"
    become: yes
    copy:
      src: ~/docker/step1-iptables.sh
      dest: /home/star/k8s/
      mode: 0644
    tags:
      - final
  

  - name: "execute shell script copied"
    become: yes
    command:
      sh /home/star/k8s/step1-iptables.sh
    tags:
      - final

  - name: "Install Kubeadm kubelet "
    become: yes
    yum:
     name: "{{ packages }}"
     state: present
     disable_excludes: kubernetes
    vars:
     packages:
      - kubelet  
      - kubeadm
      - kubectl
    tags:
      - final
      
  - name: "Launch kubeadm init with  advertise adress to ip-adress of the master host and store the kubadm join tocken into a file"
    become: yes
    shell:
      cmd: |
        sysctl net.bridge.bridge-nf-call-iptables=1
        export IPADDR=$(hostname -i)
        kubeadm init --pod-network-cidr=10.10.0.0/16 --apiserver-advertise-address=192.168.56.50 > /home/star/kubadmjoin_token.info 
    tags:
      - final
    when: groups['master'] is defined and inventory_hostname in groups['master']

  - name: "enable firewall on worker"
    become: yes
    shell: "sysctl net.bridge.bridge-nf-call-iptables=1"
    when: groups['worker'] is defined and inventory_hostname in groups['worker']
    tags:
      - final

  - name: "enable kubelet and give non root user to use kuberenets and apply CNI weave network"
    become: yes
    shell:
      cmd: |
        systemctl enable --now kubelet
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
        kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    tags:
      - final
    when: groups['master'] is defined and inventory_hostname in groups['master']
  

  - name: "waiting for coredns and proxy to startup 2min "
    wait_for:
      timeout: 120
    when: groups['master'] is defined and inventory_hostname in groups['master']

  
  - name: "enable kubelet in other nodes"
    become: yes
    shell: "systemctl enable --now kubelet "
    when: groups['worker'] is defined and inventory_hostname in groups['worker']
    tags:
      - final3

  - name: "Create variable from command kubadm create token"
    become: yes
    shell: kubeadm token create --print-join-command
    register: command_output
    tags:
      - final
    when: groups['master'] is defined and inventory_hostname in groups['master']

  - name: set join command
    set_fact:
      join_command: "{{ command_output.stdout_lines[0] }}"
    tags:
      - final3
    when: groups['master'] is defined and inventory_hostname in groups['master']

  - name: "Joining worker node"
    become: yes
    shell: "{{ hostvars[groups['master'][0]]['join_command'] }} >> /home/star/node_joined.txt "
    when: groups['worker'] is defined and inventory_hostname in groups['worker']
    tags:
      - final